name: eclipse-kura
version: 1.0
summary: Kura offers a container for M2M applications running in service gateways
description: Kura aims at offering a Java/OSGi-based container for M2M applications running in service gateways.
icon: logo.png


# apps:
#  tomcat:
#    command: bin/wrapper
#    daemon: simple
#    caps:
#    - network-client
#    - network-service

# KURA DEPS
#
# hostapd
# isc-dhcp-server
# iw
# dos2unix
# bind9

parts:

  install-jdk:
    plugin: jdk
    source: .
    build-packages:
      - ca-certificates-java

  target-platform:
    plugin: maven
    maven-options:
      - -f target-platform/pom.xml
      - -DskipTests
    source: https://github.com/eclipse/kura
    source-type: git
    source-branch: KURA_1.3.0_RELEASE

  can-support:
    after:
      - target-platform
    plugin: maven
    maven-options:
      - -Dmaven.test.skip=true
      - -f kura/manifest_pom.xml
      - -Pcan
    source: https://github.com/eclipse/kura
    source-type: git
    source-branch: KURA_1.3.0_RELEASE

  web-ui:
    after:
      - target-platform
    plugin: maven
    maven-options:
      - -Dmaven.test.skip=true
      - -f kura/pom_pom.xml
      - -Pweb
    source: https://github.com/eclipse/kura
    source-type: git
    source-branch: KURA_1.3.0_RELEASE
    stage-packages:
      - hostapd
      - iw
      - dos2unix
      - bind9
      - isc-dhcp-server

#   build:
#     after:
#       - jdk
#     plugin: make
#     source: .
#     build-packages:
# #      - mvn
#
#     stage-packages:
#       - hostapd
#       - iw
#       - dos2unix
#       - bind9
#       - isc-dhcp-server
