name: eclipse-kura
version: 1.0
summary: Kura offers a container for M2M applications running in service gateways
description: Kura aims at offering a Java/OSGi-based container for M2M applications running in service gateways.
icon: logo.png


# apps:
#  tomcat:
#    command: bin/wrapper
#    daemon: simple
#    caps:
#    - network-client
#    - network-service

# KURA DEPS
#
# hostapd
# isc-dhcp-server
# iw
# dos2unix
# bind9

parts:

  jdk:
    plugin: jdk
    source: .

  build:
    after:
      - jdk
    plugin: make
    source: .
    build-packages:
      - hostapd
      - iw
      - dos2unix
      - bind9
      - isc-dhcp-server
