name: eclipse-kura
version: 1.0
summary: Kura offers a container for M2M applications running in service gateways
description: Kura aims at offering a Java/OSGi-based container for M2M applications running in service gateways.
icon: logo.png


apps:
 kura:
   command: bin/launch
   daemon: simple
   uses: [javadude]

uses:
  javadude:
    type: migration-skill
    security-override:
      read-paths:
        - /etc/hosts
        - /etc/host.conf
      # write-paths:
      #   -
      syscalls:
        - shutdown
    caps:
     - network-client
     - network-listener
     - network-service

parts:

  install-jdk:
    plugin: jdk
    source: .
    build-packages:
      - ca-certificates-java

  kura-build:
    after:
      - install-jdk
    plugin: make
    source: .
    build-packages:
     - maven
     - wget
     - dpkg
    stage-packages:
      - hostapd
      - iw
      - dos2unix
      - bind9
      - isc-dhcp-server
      - unzip
      - ethtool
      - telnet
  launcher:
    plugin: copy
    files:
      start.sh: bin/launch
